on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Install API Catalog CLI
        run: npm install -g api-catalog-cli@latest
      - name: Catalog an API
        run: api-catalog help
      - name: REST API with curl
        run: |
          curl -X GET "https://example.com/api/v2/endpoint"
      - name: Another way to call an API
        uses: fjogeleit/http-request-action@v1
        id: api
        with:
          url: 'https://httpbin.org/get'
          method: 'GET'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"key_1": "value_1", "key_2": "value_2"}'
      - name: Get the output time
        run: echo "Result from API ${{ fromJson(steps.api.outputs.reponse).url }}"
